name: Pipeline

on:
  pull_request:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: Create tag
        id: create_tag
        uses: anothrNick/github-tag-action@master
        env:
          RELEASE_BRANCHES: .*

      - name: Create release
        id: create_release
        uses: actions/create-release@master
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: ${{ steps.create_tag.outputs.new_tag }}
          body: This is a build of the game executed by the pipeline. It is not necessarily master.
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}

  build:
    name: Build ${{ matrix.targetPlatform }}
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        targetPlatform:
          - StandaloneLinux64
          - WebGL
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          lfs: true

      - name: Prepare Unity library cache
        uses: actions/cache@master
        with:
          path: Library
          key: Library

      - name: Build game
        uses: webbertakken/unity-builder@master
        with:
          unityVersion: 2019.2.17f1
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Compress build artifact
        uses: montudor/action-zip@master
        with:
          args: zip -qq -r build.zip build

      - name: Upload build artifact to release
        uses: actions/upload-release-asset@master
        with:
          upload_url: ${{ needs.create_release.outputs.release_upload_url }}
          asset_path: build.zip
          asset_name: ${{ matrix.targetPlatform }}-Build
          asset_content_type: application/zip